site_name: Data Nebraska
site_url: https://datanebraska.com
nav:
    - Home: index.md
    - Campaign Finance: 
      - Campaign Finance Home: campaign_finance/index.md
      - Filers: campaign_finance/filers.md
      - Payors: campaign_finance/payors.md
      - Payees: campaign_finance/payees.md
      - Pillen: campaign_finance/pillen.md
    - Twitter Bots: bots.md  
    # - Random: random.md
    - Tags: tags.md              
    - About: about.md
        
theme:
    name: material
    features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs 
    - header.autohide
    - content.code.annotate # (1) 
    # favicon: assets/material/robot-angry    
    icon:
      logo: material/corn
    font:
      text: Roboto
#     #   # text: Eater
#     #   # text: Bangers
#     #   # text: Press Start 2P
      code: Roboto Mono
    palette: 
      - scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
        primary: blue
        accent: red          
      - scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to light mode
        primary: blue
        accent: red              

    nav_style: dark
    analytics:
        gtag: G-M9XK9BXB2G        
    highlightjs: true
    hljs_languages:
        - sql
        - powershell
        - python    

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/datanebraska
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-M9XK9BXB2G      

plugins:
  - search:
  - tags:
      tags_file: tags.md  
      # prebuild_index: true  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.number.js
  - javascripts/tablesort.date.js
  - javascripts/tablesort.js
  


markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - admonition
  - pymdownx.details
  - pymdownx.superfences 
  - attr_list      
  - abbr
  - pymdownx.snippets  
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true   
  
  
     