site_name: Evil Bot Corp


nav:
    - Home: index.md
    - Make Bots: bots.md                
    - About: about.md
        
theme:
    name: material
    nav_style: dark
    analytics:
        gtag: G-M9XK9BXB2G        
    highlightjs: true
    hljs_languages:
        - sql
        - powershell
        - python    


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences        